site_name: nodeserial
repo_url: https://github.com/rodolfomarianocy/nodeserial
repo_name: rodolfomarianocy/nodeserial
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/nodeserial.png
  favicon: assets/nodeserial.png


markdown_extensions:
  - attr_list

extra_css:
  - css/center.css